# Generated by Django 2.0.4 on 2018-04-21 18:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180421_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
