# Generated by Django 2.0.4 on 2018-05-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_artist_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-release_date']},
        ),
    ]
