# Generated by Django 2.0.4 on 2018-05-11 15:26

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20180508_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='todo',
            field=models.BooleanField(default=False, verbose_name='TODO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='features',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='music.FeatureThru', to='music.Feature', verbose_name='Features'),
        ),
    ]
