# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('affiliation', models.CharField(max_length=100, verbose_name='Affiliation')),
                ('start_date', models.DateField(verbose_name='Start Time')),
                ('ongoing', models.BooleanField(verbose_name='Ongoing')),
                ('end_date', models.DateField(verbose_name='End Time')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('school', models.CharField(max_length=100, verbose_name='Institution')),
                ('start_date', models.DateField(verbose_name='Start Time')),
                ('ongoing', models.BooleanField(verbose_name='Ongoing')),
                ('end_date', models.DateField(verbose_name='End Time')),
                ('graduation', models.DateField(verbose_name='Graduation')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('gpa', models.FloatField(verbose_name='GPA')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('employment', models.CharField(max_length=100, verbose_name='Institution')),
                ('start_date', models.DateField(verbose_name='Start Time')),
                ('ongoing', models.BooleanField(verbose_name='Ongoing')),
                ('end_date', models.DateField(verbose_name='End Time')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Employment')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('name', models.CharField(max_length=50, verbose_name='Experience Name')),
                ('exp_type', models.CharField(max_length=20, verbose_name='Experience Type')),
                ('start_date', models.DateField(verbose_name='Start Time')),
                ('ongoing', models.BooleanField(verbose_name='Ongoing')),
                ('end_date', models.DateField(verbose_name='End Time')),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('keyword', models.CharField(max_length=20, verbose_name='Keyword')),
                ('archived', models.BooleanField(verbose_name='Archived')),
            ],
        ),
    ]
