# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 02:11
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('start_date', models.DateField(verbose_name='Start Time')),
                ('ongoing', models.BooleanField(verbose_name='Ongoing')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Time')),
                ('name', models.CharField(max_length=100, verbose_name='Affiliation')),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffiliationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('point_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('affiliation', adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Affiliation')),
            ],
            options={
                'verbose_name_plural': 'Affiliation Points',
                'ordering': ['point_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('start_date', models.DateField(verbose_name='Start Time')),
                ('ongoing', models.BooleanField(verbose_name='Ongoing')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Time')),
                ('school', models.CharField(max_length=100, verbose_name='Institution')),
                ('graduation', models.DateField(verbose_name='Graduation')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('gpa', models.FloatField(verbose_name='GPA')),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('point_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('text', models.TextField(verbose_name='Text')),
                ('keyword', models.CharField(max_length=50, null=True, verbose_name='Keyword')),
                ('education', adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Education')),
            ],
            options={
                'verbose_name_plural': 'Education Points',
                'ordering': ['point_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('start_date', models.DateField(verbose_name='Start Time')),
                ('ongoing', models.BooleanField(verbose_name='Ongoing')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Time')),
                ('name', models.CharField(max_length=100, verbose_name='Institution')),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('point_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('employment', adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Employment')),
            ],
            options={
                'verbose_name_plural': 'Employment Points',
                'ordering': ['point_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('start_date', models.DateField(verbose_name='Start Time')),
                ('ongoing', models.BooleanField(verbose_name='Ongoing')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Time')),
                ('name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('exp_type', models.CharField(max_length=20, verbose_name='Project Type')),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('point_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('experience', adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Project')),
            ],
            options={
                'verbose_name_plural': None,
                'ordering': ['point_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=25, verbose_name='Keyword')),
                ('text', models.TextField(verbose_name='Text')),
                ('archived', models.BooleanField(verbose_name='Archived')),
            ],
        ),
    ]
