# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End Time'),
        ),
    ]
