# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 01:50
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20170923_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliationpoint',
            options={'ordering': ['point_order'], 'verbose_name_plural': 'Affiliation Points'},
        ),
        migrations.AlterModelOptions(
            name='employmentpoint',
            options={'ordering': ['point_order'], 'verbose_name_plural': 'Employment Points'},
        ),
        migrations.AlterModelOptions(
            name='experiencepoint',
            options={'ordering': ['point_order'], 'verbose_name_plural': 'Experience Points'},
        ),
        migrations.RemoveField(
            model_name='affiliationpoint',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employmentpoint',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='experiencepoint',
            name='experience',
        ),
        migrations.AddField(
            model_name='affiliationpoint',
            name='affiliation_foreign',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Affiliation'),
        ),
        migrations.AddField(
            model_name='affiliationpoint',
            name='point_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='employmentpoint',
            name='employment_foreign',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Employment'),
        ),
        migrations.AddField(
            model_name='employmentpoint',
            name='point_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='experiencepoint',
            name='experience_foreign',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Experience'),
        ),
        migrations.AddField(
            model_name='experiencepoint',
            name='point_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
