# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20170924_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='keyword',
            field=models.CharField(max_length=25, verbose_name='Keyword'),
        ),
    ]
