# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20170924_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliationpoint',
            old_name='affiliation_foreign',
            new_name='affiliation',
        ),
        migrations.RenameField(
            model_name='employmentpoint',
            old_name='employment_foreign',
            new_name='employment',
        ),
        migrations.RenameField(
            model_name='experiencepoint',
            old_name='experience_foreign',
            new_name='experience',
        ),
    ]
