# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20170924_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Time'),
        ),
    ]
