# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20170924_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliation',
            old_name='affiliation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='employment',
            new_name='name',
        ),
    ]
