# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 04:06
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20170925_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(verbose_name='Archived')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('point_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('education', adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Experience')),
            ],
            options={
                'verbose_name_plural': 'Education Points',
                'ordering': ['point_order'],
                'abstract': False,
            },
        ),
    ]
