# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 04:11
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_educationpoint_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationpoint',
            name='education',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Education'),
        ),
    ]
