# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20170925_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationpoint',
            name='keyword',
            field=models.CharField(max_length=200, null=True, verbose_name='Keyword'),
        ),
    ]
