# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20170925_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationpoint',
            name='keyword',
            field=models.CharField(max_length=50, null=True, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='educationpoint',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
